name: monthly-ipvn-time-series-pipeline

on:
  schedule:
  - cron: '30 16 * * *'
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.11
  POETRY_VERSION: 1.7.0
  POETRY_URL: https://install.python-poetry.org



jobs:

  monthly-ipvn-time-series-pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install Dependencies
      run: poetry install
      if: steps.cache.outputs.cache-hit != 'true'

    - name: execute python workflows from bash script
      env:
        HOPSWORKS_API_KEY: ${{secrets.HOPSWORKS_API_KEY}}
      run: poetry run jupyter nbconvert --to notebook --execute notebooks/05_backfill_feature_store.ipynb